using System;
using _ImmersiveGames.NewScripts.ActorSystem.Contracts.Inbound;

namespace _ImmersiveGames.NewScripts.ActorSystem.ReadModel
{
    /// <summary>
    /// Minimal semantic read model generated by ActorSystem.
    /// </summary>
    public readonly struct ActorSystemReadModelSnapshot : IEquatable<ActorSystemReadModelSnapshot>
    {
        public ActorSystemReadModelSnapshot(
            ActorSystemSemanticContext context,
            string relevantActorId,
            int runtimeActorCount,
            string reason)
        {
            Context = context;
            RelevantActorId = Normalize(relevantActorId);
            RuntimeActorCount = runtimeActorCount < 0 ? 0 : runtimeActorCount;
            Reason = Normalize(reason);
        }

        public ActorSystemSemanticContext Context { get; }
        public string RelevantActorId { get; }
        public int RuntimeActorCount { get; }
        public string Reason { get; }

        public bool IsValid => Context.IsValid;
        public bool HasRelevantActor => !string.IsNullOrWhiteSpace(RelevantActorId);

        public static ActorSystemReadModelSnapshot Empty => new(
            ActorSystemSemanticContext.Empty,
            string.Empty,
            0,
            string.Empty);

        public bool Equals(ActorSystemReadModelSnapshot other)
        {
            return Context.Equals(other.Context) &&
                   string.Equals(RelevantActorId, other.RelevantActorId, StringComparison.Ordinal) &&
                   RuntimeActorCount == other.RuntimeActorCount &&
                   string.Equals(Reason, other.Reason, StringComparison.Ordinal);
        }

        public override bool Equals(object obj)
        {
            return obj is ActorSystemReadModelSnapshot other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                int hashCode = Context.GetHashCode();
                hashCode = (hashCode * 397) ^ StringComparer.Ordinal.GetHashCode(RelevantActorId ?? string.Empty);
                hashCode = (hashCode * 397) ^ RuntimeActorCount;
                hashCode = (hashCode * 397) ^ StringComparer.Ordinal.GetHashCode(Reason ?? string.Empty);
                return hashCode;
            }
        }

        public override string ToString()
        {
            string relevantActorId = string.IsNullOrWhiteSpace(RelevantActorId) ? "<none>" : RelevantActorId;
            string reason = string.IsNullOrWhiteSpace(Reason) ? "<none>" : Reason;
            return $"context='{Context}', relevantActorId='{relevantActorId}', runtimeActorCount='{RuntimeActorCount}', reason='{reason}'";
        }

        private static string Normalize(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? string.Empty : value.Trim();
        }
    }
}